### ISSUE TITLE
Classify with Decision Tree

### ISSUE THREAD

**Issue by Coop8** [galaxybomb23/Decision-Tree-Plus-Plus#19]
- [x] recursiveDescentForClassification
- [x] classify
~~classifyByAskingQuestions~~
~~interactiveRecursiveDescentForClassification~~

**Comment by galaxybomb23** [comment]
Moving ` classifyByAskingQuestions` and `interactiveRecursiveDescentForClassification` to #38  as they are non-baseline and warrant their own issue.
