### ISSUE TITLE
Create Python interface

### ISSUE THREAD

**Issue by galaxybomb23** [galaxybomb23/Decision-Tree-Plus-Plus#24]
Per the Spec, the C++ library needs to be callable by python. This issue plans to address this by making new wrappers for each function

**Comment by Nandini1071** [comment]
Hi @galaxybomb23 is this issue still open, if yes then what is the requirement would like to contribute on this.

**Comment by galaxybomb23** [comment]
Hello @Nandini1071, I wanted to inform you that we’re in the final steps of closing out this issue. Since this is a senior design project involving @iBoot32, @Coop8, and myself, we're moving through a rapid prototyping phase, aiming for completion by December.

While we can’t delegate tasks externally to ensure we stay on track, you’re welcome to work on a fork, submit a pull request, or even propose your own enhancements. We’d be happy to review any contributions you make.

Feel free to explore more about Decision Trees here ([link](https://engineering.purdue.edu/kak/Tutorials/DecisionTreeClassifiers.pdf)) if this topic catches your interest!
