### ISSUE TITLE
Interactive Classification with Decision Tree

### ISSUE THREAD

**Issue by galaxybomb23** [galaxybomb23/Decision-Tree-Plus-Plus#38]
Moved ` classifyByAskingQuestions` and `interactiveRecursiveDescentForClassification`  from #19 

Deliverables:

- [x] classifyByAskingQuestions
- [x] interactiveRecursiveDescentForClassification

**Comment by Coop8** [comment]
Functions are done, gotta clean up code, style the output to the terminal better, test more, and write doxygen comments.
