### ISSUE TITLE
Decision Tree Class

### ISSUE THREAD

**Issue by galaxybomb23** [galaxybomb23/Decision-Tree-Plus-Plus#5]
![Image](https://github.com/user-attachments/assets/f4719831-8f0b-4b3c-b621-d14bed28f0ca)

- [x] Constructor and Deconstructors
- [ ] #20
- [ ] #16
- [ ] #17
- [ ] #18
- [ ] #19

**Comment by Coop8** [comment]
- [ ] Constructor and Deconstructors
- [ ] Class and Utility Functions
- [ ] Entropy Calculators
- [ ] Probability Calculators
- [ ] Construct Decision Tree
- [ ] Classify with Decision Tree
